### ISSUE TITLE
Asalam alaikum.. Need a English version of your code

### ISSUE THREAD

**Issue by ASKbytes** [noplanalderson/simasjid#4]
I need a english version of this code . including database tables / colum names. this is help all countries masjids. Kindly do the needful

**Comment by noplanalderson** [comment]
Wa'alaikumussalaam
I have to do a major update for the request, and I don't have enough time to do it right now
But it's a good idea, thanks for the advice. I will consider it for the next update

**Comment by ASKbytes** [comment]
Hi,  Atleast i need a English translation for the DB tables, kindly send me here. thanks in advance

**Comment by noplanalderson** [comment]
Ok, soon
i'll create db tables translation

**Comment by ASKbytes** [comment]
Asalam alaikum brother, Can i get the DB Tables  translation. ?  please help me.
